org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.java.home=/Users/shuaizhexu/Applications/Android Studio Narwhal 4 Feature Drop 2025.1.4.app/Contents/jbr/Contents/Home
android.useAndroidX=true
android.enableJetifier=true
